### ISSUE TITLE
Webpack error "Insufficient number of arguments or no entry found"

### ISSUE THREAD

**Issue by farmerpaul** [akillmer/shopify-theme-sync-plugin#2]
Hi there,

I'm just trying to get started using your webpack plugin, and I'm assuming I just haven't set things up properly. I've always struggled to wrap my head around webpack, although I use it in almost all my projects, but it's always based on someone else's `webpack.config.js`. With your plugin, it seems like I'm expected to write it from scratch, which is slightly daunting, so I've just based it entirely on your example. Maybe I need to add more to it, but I'd have no idea what.

I placed all the theme source files under my project root (`/assets`, `/config`, `/layout`, and so on). That wasn't mentioned in your README so I just made an assumption there.

When I run `webpack --watch`, it outputs this:

```
webpack is watching the files…


Insufficient number of arguments or no entry found.
Alternatively, run 'webpack(-cli) --help' for usage info.

Hash: 109447b0a9e1e8f0b305
Version: webpack 4.44.1
Time: 5317ms
Built at: 2020-08-26 2:46:18 p.m.

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/

ERROR in Entry module not found: Error: Can't resolve './src' in '/Users/paul/Projects/greenbeingfarm/shopify/theme'
```

- I don't know how to solve this "insufficient number of arguments or no entry found" error - perhaps because webpack still generally confounds me.
- Regarding not being able to resolve `./src`, I tried creating this directory, and it didn't make a difference – that error still shows up.
- I'm sure I can work out that warning about the "mode" option, I'm just trying to focus on the other issues first.

Here's my `webpack.config.js`:

```js
const ShopifyThemeSyncPlugin = require('shopify-theme-sync-plugin');

module.exports = {
  plugins: [
    new ShopifyThemeSyncPlugin({
      storeUrl: 'https://https://greenbeingfarm.myshopify.com/',
      port: 8888,
      env: 'production',
      delay: 500,
      browsersync: {
        ui: false,
        logLevel: 'silent',
        ignore: ['*.json'],
      },
    }),
  ],
};
```

Here's my `package.json`:

```json
{
  "name": "greenbeingfarm",
  "version": "1.0.0",
  "description": "Green Being Farm Theme",
  "repository": "https://gitlab.com/farmerpaul/greenbeingfarm",
  "author": "Paul Hoepfner-Homme",
  "license": "MIT",
  "private": true,
  "devDependencies": {
    "browser-sync": "^2.26.12",
    "shopify-theme-sync-plugin": "^1.0.3",
    "webpack": "^4.44.1",
    "webpack-cli": "^3.3.12"
  },
  "scripts": {
    "start": "webpack --watch"
  }
}
```

Apologies if I'm missing something extremely obvious. Since Slate was deprecated, I've struggled to find a satisfactory development framework for working on Shopify themes, since there is such a mishmash of other options involving Browsersync, or Browsersync-like tools. I'm crossing my fingers yours will be the winner!

**Comment by farmerpaul** [comment]
I discovered a workaround: apparently webpack requires a dummy JS file to work at all, so I created an empty file called `/src/main.js` (nothing in it), and re-ran webpack, and it worked! It appears to have output the file to `/dist` though, so I'll have to do some research to figure out how to make it output to `/assets` like your README says.

I would suggest adding a couple of these clues to your README. With webpack as confusing a tool as it is, it helps to have a little context on how to get it minimally set up wherever possible. My guess is that Shopify theme developers are probably slightly less likely to be as savvy as the average front-end developer, who might already have some way of understanding how to use webpack.

**Comment by akillmer** [comment]
Thank you for the feedback and for the suggestions on enhancing the README, I'll definitely address the points you made.

Webpack does require an entrypoint, as you figured out, and you can specify that within `webpack.config.js`. We can change the output from `/dist` too:

```javascript
const path = require('path');

module.exports = {
  entry: '/some/path/main.js', // relative to webpack.config.js
  output: {
    path: path.resolve(__dirname, './assets'),
    filename: 'dist.js'
  },
  plugins: [ new ShopifyThemeSyncPlugin({ ... }) ]
}
```

It sounds like you'd rather use this plugin as a standalone tool (taking webpack out of the mix entirely). I think this would be a helpful feature.
